version: "3"
services:
  backend:
    container_name: laar_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    image: laarregistry.azurecr.io/laar-backend:latest
    ports:
      - "3000:3000"

  frontend:
    container_name: laar_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PORT=80
    image: laarregistry.azurecr.io/laar-frontend:latest
    ports:
      - "80:80"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
