version: "3"
services:
  backend:
    container_name: laar_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laar-backend:latest
    env_file:
      - key.env
    environment:
      - FIREBASE_KEY_JSON=${FIREBASE_KEY_JSON}
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - devnet
    healthcheck:
      test: curl --fail http://localhost:3000/api/alive || exit 1
      interval: 2s
      retries: 10
      start_period: 10s
      timeout: 10s

  frontend:
    container_name: laar_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: laar-frontend:latest
    environment:
      - VITE_PORT=5000
    ports:
      - "5000:5000"
    networks:
      - devnet
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 2s
      retries: 10
      start_period: 10s
      timeout: 10s

networks:
  devnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
