version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laar-backend:latest
    environment:
      - FIREBASE_KEY_JSON=${FIREBASE_KEY_JSON}
      - PORT=3000
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: laar-frontend:latest
    environment:
      - VITE_PORT=5000
    ports:
      - '5000:5000'
