version: "3"
services:
  backend:
    container_name: laar_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laar-backend:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - devnet
    healthcheck:
      test: curl --fail http://localhost:3000/api/alive | grep "OK" || exit 1
      interval: 60s
      retries: 10
      start_period: 10s
      timeout: 10s

  frontend:
    container_name: laar_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PORT=80
    image: laar-frontend:latest
    ports:
      - "80:80"
    networks:
      - devnet
    healthcheck:
      test: curl --fail http://localhost:80/health | grep "OK" || exit 1
      interval: 60s
      retries: 10
      start_period: 10s
      timeout: 10s

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"

networks:
  devnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
