version: "3"
services:
  backend:
    container_name: laar_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laar-backend:latest
    ports:
      - "3000:3000"
    networks:
      - devnet
    healthcheck:
      test: curl --fail http://localhost:3000/api/alive | grep "OK" || exit 1
      interval: 60s
      retries: 10
      start_period: 10s
      timeout: 10s
    hostname: api.laar.local

  frontend:
    container_name: laar_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PORT=80
    image: laar-frontend:latest
    ports:
      - "80:80"
    networks:
      - devnet
    healthcheck:
      test: curl --fail http://localhost:80/health | grep "OK" || exit 1
      interval: 60s
      retries: 10
      start_period: 10s
      timeout: 10s
    hostname: laar.local

networks:
  devnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
