import { RecommendationsType } from "../../types/recommTypes";

export const activityRecomm: RecommendationsType[] = [
  {
    category: "activity",
    title: "Ulkoilu",
    recomm: {
      pihaleikki: 3,
      kävely: 10,
      pulkkailu: 8,
      keinuminen: 8,
      leikkipuisto: 6,
      metsäretki: 12,
      vesileikit: 5,
      maja: 12,
      noitakeittiö: 24,
      jäätelökioski: 24,
      hiekkalaatikko: 8,
      seikkailu: 12,
    },
    textContent: {
      pihaleikki: "",
      kävely: "",
      pulkkailu: "",
      keinuminen: "",
      leikkipuisto: "",
      metsäretki: "",
      vesileikit: "",
      maja: "",
      noitakeittiö: "",
      jäätelökioski: "",
      hiekkalaatikko: "",
      seikkailu: "",
    },
    photos: {
      pihaleikki: "",
      kävely: "",
      pulkkailu: "",
      keinuminen: "",
      leikkipuisto: "",
      metsäretki: "",
      vesileikit: "",
      maja: "",
      noitakeittiö: "",
      jäätelökioski: "",
      hiekkalaatikko: "",
      seikkailu: "",
    },
  },
  {
    category: "activity",
    title: "Käsityöt",
    recomm: {
      sakset: 3,
      langanpujottelu: 12,
      piirtäminen: 10,
      puutyöt: 24,
      askartelu: 12,
    },
    textContent: {
      sakset: "",
      langanpujottelu: "",
      piirtäminen: "",
      puutyöt: "",
      askartelu: "",
    },
    photos: {
      sakset: "",
      langanpujottelu: "",
      piirtäminen: "",
      puutyöt: "",
      askartelu: "",
    },
  },
  {
    category: "activity",
    title: "Musiikki",
    recomm: {
      kehosoittimet: 5,
      laulaminen: 1,
      rummuttaminen: 8,
      nokkahuilu: 24,
      rytmimunat: 12,
      lelupiano: 12,
      sadutus: 18,
      satuhieronta: 1,
    },
    textContent: {
      kehosoittimet: "",
      laulaminen: "",
      rummuttaminen: "",
      nokkahuilu: "",
      rytmimunat: "",
      lelupiano: "",
      sadutus: "",
    },
    photos: {
      kehosoittimet: "",
      laulaminen: "",
      rummuttaminen: "",
      nokkahuilu: "",
      rytmimunat: "",
      lelupiano: "",
      sadutus: "",
    },
  },
  {
    category: "activity",
    title: "Taide",
    recomm: {
      värikoulu: 1,
      maalaminen: 10,
      sormivärit: 12,
      puuvärit: 18,
      vahaliidut: 18,
      vesivärit: 24,
      loru: 1,
      sanataide: 24,
    },
    textContent: {
      värikoulu: "värikoulu",
      maalamminen: "maalamminen",
      sormivärit: "sormivärit",
      puuvärit: "puuvärit",
      vahaliidut: "vahaliidut",
      vesivärit: "vesivärit",
      loru: "loru",
      sanataide: "sanataide",
    },
    photos: {
      värikoulu: "",
      maalamminen: "",
      sormivärit: "",
      puuvärit: "",
      vahaliidut: "",
      vesivärit: "",
      loru: "",
      sanataide: "",
    },
  },
  {
    category: "activity",
    title: "Liikkuminen",
    recomm: { konttaaminen: 6, hyppiminen: 6, temppurata: 2, tasapainoilu: 2 },
    textContent: {
      konttaaminen: "",
      hyppiminen: "",
      temppurata: "",
      tasapainoilu: "",
    },
    photos: {
      konttaaminen: "",
      hyppiminen: "",
      temppurata: "",
      tasapainoilu: "",
    },
  },
];
