import { RecommendationsType } from "../../types/recommTypes";

export const activityRecomm: RecommendationsType[] = [
  {
    category: "activity",
    title: "Ulkoilu",
    recomm: {
      pihaleikki: 3,
      kävely: 12,
      pulkkailu: 8,
      keinuminen: 5,
      leikkipuisto: 4,
      metsäretki: 6,
      vesileikit: 5,
      maja: 8,
      noitakeittiö: 5,
      jäätelökioski: 4,
      hiekkalaatikko: 2,
      seikkailu: 2,
    },
    textContent: {
      pihaleikki: "",
      kävely: "",
      pulkkailu: "",
      keinuminen: "",
      leikkipuisto: "",
      metsäretki: "",
      vesileikit: "",
      maja: "",
      noitakeittiö: "",
      jäätelökioski: "",
      hiekkalaatikko: "",
      seikkailu: "",
    },
    photos: {
      pihaleikki: "",
      kävely: "",
      pulkkailu: "",
      keinuminen: "",
      leikkipuisto: "",
      metsäretki: "",
      vesileikit: "",
      maja: "",
      noitakeittiö: "",
      jäätelökioski: "",
      hiekkalaatikko: "",
      seikkailu: "",
    },
  },
  {
    category: "activity",
    title: "Käsityöt",
    recomm: {
      sakset: 3,
      langanpujottelu: 12,
      piirtäminen: 8,
      puutyöt: 5,
      askartelu: 4,
    },
    textContent: {
      sakset: "",
      langanpujottelu: "",
      piirtäminen: "",
      puutyöt: "",
      askartelu: "",
    },
    photos: {
      sakset: "",
      langanpujottelu: "",
      piirtäminen: "",
      puutyöt: "",
      askartelu: "",
    },
  },
  {
    category: "activity",
    title: "Musiikki",
    recomm: {
      kehosoittimet: 3,
      laulaminen: 12,
      rummuttaminen: 8,
      nokkahuilu: 5,
      rytmimunat: 4,
      lelupiano: 4,
      sadutus: 4,
      satuhieronta: 2,
    },
    textContent: {
      kehosoittimet: "",
      laulaminen: "",
      rummuttaminen: "",
      nokkahuilu: "",
      rytmimunat: "",
      lelupiano: "",
      sadutus: "",
    },
    photos: {
      kehosoittimet: "",
      laulaminen: "",
      rummuttaminen: "",
      nokkahuilu: "",
      rytmimunat: "",
      lelupiano: "",
      sadutus: "",
    },
  },
  {
    category: "activity",
    title: "Taide",
    recomm: {
      värikoulu: 1,
      maalamminen: 6,
      sormivärit: 2,
      puuvärit: 2,
      vahaliidut: 3,
      vesivärit: 5,
      loru: 4,
      sanataide: 5,
    },
    textContent: {
      värikoulu: "värikoulu",
      maalamminen: "maalamminen",
      sormivärit: "sormivärit",
      puuvärit: "puuvärit",
      vahaliidut: "vahaliidut",
      vesivärit: "vesivärit",
      loru: "loru",
      sanataide: "sanataide",
    },
    photos: {
      värikoulu: "",
      maalamminen: "",
      sormivärit: "",
      puuvärit: "",
      vahaliidut: "",
      vesivärit: "",
      loru: "",
      sanataide: "",
    },
  },
  {
    category: "activity",
    title: "Liikkuminen",
    recomm: { konttaaminen: 1, hyppiminen: 6, temppurata: 2, tasapainoilu: 2 },
    textContent: {
      konttaaminen: "",
      hyppiminen: "",
      temppurata: "",
      tasapainoilu: "",
    },
    photos: {
      konttaaminen: "",
      hyppiminen: "",
      temppurata: "",
      tasapainoilu: "",
    },
  },
];
