name: CI-DEPLOY

on:
  push:
    branches:
      - main
      - deployment-test

jobs:
  build-push-deploy:
    runs-on: [self-hosted, deploy]
    environment: production
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.AZR_USERNAME_ID }}
          password: ${{ secrets.AZR_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker CLI
        run: |
          uname -a
          docker info

      - name: Build and Push backend image
        run: |
          docker buildx create
          docker buildx build --platform linux/amd64 -t ${{ secrets.ACR_REGISTRY }}/laar-backend:latest --push ./backend

      - name: Build and Push frontend image
        run: |
          docker buildx create
          docker buildx build --platform linux/amd64 -t ${{ secrets.ACR_REGISTRY }}/laar-frontend:latest --build-arg PORT=80 --push ./frontend

      - name: Deploy to Azure Container Registry
        run: |

          az acr task create \
            --registry ${{ secrets.ACR_REGISTRY }} \
            --name laar-backend-deploy \
            --file ./backend/Dockerfile \
            --image ${{ secrets.ACR_REGISTRY }}/laar-backend:latest \
            --context-path .

          az acr task create \
            --registry ${{ secrets.ACR_REGISTRY }} \
            --name laar-frontend-deploy \
            --file ./frontend/Dockerfile \
            --image ${{ secrets.ACR_REGISTRY }}/laar-frontend:latest \
            --arg PORT=80 \
            --context-path .
