name: CI-DEPLOY

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: [self-hosted, deploy]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
