name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: [self-hosted, deploy]
    environment: production
    steps:
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.AZR_USERNAME_ID }}
          password: ${{ secrets.AZR_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push backend image
        run: |
          docker buildx create
          docker buildx build --platform linux/amd64 -t ${{ secrets.ACR_REGISTRY }}/laar-backend:latest --push ./backend

      - name: Build and Push frontend image
        env:
          VITE_API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}" > frontend/.env
          docker buildx create
          docker buildx build --platform linux/amd64 -t ${{ secrets.ACR_REGISTRY }}/laar-frontend:latest --build-arg PORT=80 --push ./frontend
