name: Deploy docs to Github Pages

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, feature]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Clear npm cache
        run: |
          echo "Initializing local environment"
          npm cache clean --force
          npm cache verify

      - name: Set up utils
        working-directory: utils
        run: |
          npm install

      - name: Build docs folder
        working-directory: utils
        run: |
          npm run build-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
