name: Deploy docs to Github Pages

on:
  push:
    branches:
      - dev

jobs:
  test-coverage-deploy-docs:
    runs-on: [self-hosted, feature]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Clear npm cache
        run: |
          echo "Initializing local environment"
          npm cache clean --force
          npm cache verify

      - name: Set up backend
        working-directory: backend
        run: |
          echo "Installing backend dependencies"
          npm install

      - name: Run backend tests
        working-directory: backend
        run: |
          echo "Running backend tests"
          npm run test

      - name: Copy coverage to docs
        run: |
          cd ./backend/coverage/lcov-report && find . -type f | grep -vE "\.(js|ts|tsx)\.html$" | rsync -av --files-from=- . ../../../docs/backendcoverage/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
