name: CI-FEATURE

on:
  pull_request:
    branches:
      - dev

jobs:
  build-backend-run-tests:
    runs-on: [self-hosted, feature]
    env:
      FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Clear npm cache
        run: |
          echo "Initializing local environment"
          npm cache clean --force
          npm cache verify

      - name: Set up backend
        working-directory: backend
        run: |
          npm install
          npm run build

      - name: Run tests
        working-directory: backend
        run: |
          npm run test

      - name: Parse results
        id: parse_results
        working-directory: utils
        run: |
          npm install
          node html-to-json.js
          node json-to-markdown.js
          content=$(cat output.md | awk '{print $0"\n"}')
          echo "::set-output name=content::$content"
        shell: bash

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "${{ steps.parse_results.outputs.content }}"
          comment_tag: "backend-test-results"

      - name: Run backend
        run: |
          (
            cd backend
            PORT=3000 FIREBASE_KEY_JSON=${FIREBASE_KEY_JSON} npm run start
          ) &
          bash ./check-healthy-light.sh "Backend" "http://localhost:3000/api/alive" 120
