name: CI-FEATURE

on:
  pull_request:
    branches:
      - dev

jobs:
  build-backend-run-tests:
    runs-on: [self-hosted, feature]
    env:
      FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/*.lock') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Set up backend
        working-directory: backend
        run: |
          npm install
          npm run build

      - name: Run tests
        working-directory: backend
        run: |
          npm run test

      - name: Parse results
        if: success() || failure()
        id: parse_results
        working-directory: utils
        run: |
          npm install
          title="Backend Coverage Summary"
          path="backend"
          file="backend-summary"
          node html-to-json.js "$path" "$file"
          node json-to-markdown.js "$title" "$file" "$path"
          echo "::set-output name=file::$file"
        shell: bash

      - name: Comment PR
        if: success() || failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: "utils/results/${{ steps.parse_results.outputs.file }}.md"
          comment_tag: "backend-test-results"

      - name: Run backend
        run: |
          (
            cd backend
            PORT=3000 FIREBASE_KEY_JSON=${FIREBASE_KEY_JSON} npm run start
          ) &
          bash ./check-healthy-light.sh "Backend" "http://localhost:3000/api/alive" 120

  build-frontend-run-tests:
    runs-on: [self-hosted, feature]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/*.lock') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Setup frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Run tests
        working-directory: frontend
        run: |
          npm run test

      - name: Parse results
        if: success() || failure()
        id: parse_results
        working-directory: utils
        run: |
          npm install
          title="Frontend Coverage Summary"
          path="frontend"
          file="frontend-summary"
          node html-to-json.js "$path" "$file"
          node json-to-markdown.js "$title" "$file" "$path"
          echo "::set-output name=file::$file"
        shell: bash

      - name: Comment PR
        if: success() || failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: "utils/results/${{ steps.parse_results.outputs.file }}.md"
          comment_tag: "frontend-test-results"

      - name: Run frontend
        run: |
          (
            cd frontend
            VITE_PORT=5000 npm run preview
          ) &
          bash ./check-healthy-light.sh "Frontend" "http://localhost:5000" 120
