name: CI-LOCAL

on:
  push:
    branches:
      - local/test

jobs:
  local-backend-build:
    runs-on: [self-hosted, local]
    env:
      FIREBASE_KEY_JSON: $FIREBASE_KEY_JSON
    steps:
      - name: Debug Token
        run: |
          echo "FIREBASE_KEY_JSON=${FIREBASE_KEY_JSON}" >> key.env

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Set up backend
        run: |
          cd backend
          npm install
          npm run build

      - name: Run backend
        run: |
          cd backend
          PORT=3000 FIREBASE_KEY_JSON=${FIREBASE_KEY_JSON} npm run start
  local-frontend-build:
    runs-on: [self-hosted, local]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Set up frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Run frontend
        run: |
          cd frontend
          VITE_PORT=5000 npm run preview
  local-verify-alive:
    runs-on: [self-hosted, local]
    steps:
      - name: Verify services are alive
        run: |
          echo $PWD
          sudo bash ./check-healthy-light.sh
