name: CI-LOCAL

on:
  push:
    branches:
      - local/test

jobs:
  local-build:
    runs-on: self-hosted
    env:
      FIREBASE_KEY_JSON: $FIREBASE_KEY_JSON
    steps:
      - name: Debug Token
        run: |
          echo "FIREBASE_KEY_JSON=${FIREBASE_KEY_JSON}" >> key.env

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Set up Docker Compose
        run: |
          sudo docker compose up --build -d
          sudo docker ps -a

      - name: Wait for healthchecks
        run: |
          bash ./check-healthy.sh

      - name: Tear down Docker Compose
        run: |
          sudo docker compose down
