name: Test workflow

on:
  push:
    branches:
      - feature/KANBAN-165*

jobs:
  build-backend-run-tests:
    runs-on: [self-hosted, feature]
    env:
      FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-backend-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Set up backend
        working-directory: backend
        run: |
          npm install
          npm run build

      - name: Run tests
        working-directory: backend
        run: |
          npm run test

      - name: Parse results
        if: success() || failure()
        id: parse_results
        working-directory: utils
        run: |
          npm install
          title="Backend Coverage Summary"
          path="backend"
          file="backend-summary"
          node html-to-json.js "$path" "$file"
          node json-to-markdown.js "$title" "$file" "$path"
          echo "::set-output name=file::$file"
        shell: bash

      - name: Run backend
        run: |
          (
            cd backend
            PORT=3000 FIREBASE_KEY_JSON=${FIREBASE_KEY_JSON} npm run start
          ) &
          bash ./check-healthy-light.sh "Backend" "http://localhost:3000/api/alive" 120

  build-frontend-run-tests:
    runs-on: [self-hosted, deploy]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-frontend-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Setup frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Run tests
        working-directory: frontend
        run: |
          npm run test

      - name: Parse results
        if: success() || failure()
        id: parse_results
        working-directory: utils
        run: |
          npm install
          title="Frontend Coverage Summary"
          path="frontend"
          file="frontend-summary"
          node parse-frontend-results.js
          node html-to-json.js "$path" "$file"
          node json-to-markdown.js "$title" "$file" "$path"
          echo "::set-output name=file::$file"
        shell: bash

      - name: Run frontend
        run: |
          (
            cd frontend
            VITE_PORT=5000 npm run preview
          ) &
          bash ./check-healthy-light.sh "Frontend" "http://localhost:5000" 120

  run-prettier:
    runs-on: [self-hosted, feature]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Run prettier
        run: |
          npx prettier . --check &> utils/results/prettier-summary.txt || true
          cd utils
          node prettier-parser.js

      - name: Display results in actions summary
        if: always()
        run: echo "::set-output name=GITHUB_STEP_SUMMARY::$(cat utils/results/prettier-summary.md)"
