name: Release branch testing actions

on:
  push:
    branches:
      - release/*

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Set up Docker Compose
        run: |
          docker network prune -f
          FIREBASE_KEY_JSON='${{ secrets.FIREBASE_KEY_JSON }}' docker compose -f docker-compose.release.yml up --build -d 
          docker ps -a

      - name: Wait for healthchecks
        run: |
          bash ./check-healthy.sh
          bash ./check-secret.sh

      - name: Cleanup
        if: success() || failure()
        run: |
          echo "Cleaning up..."
          docker compose -f docker-compose.release.yml down
