name: CI-RELEASE

on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest
    env:
      FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Set env variables
        run: |
          echo "FIREBASE_KEY_JSON=$FIREBASE_KEY_JSON" >> key.env

      - name: Set up Docker Compose
        run: |
          sudo docker compose up --build -d 
          sudo docker ps -a

      - name: Wait for healthchecks
        run: |
          bash ./check-healthy.sh

      - name: Cleanup
        if: success() || failure()
        run: |
          echo "Cleaning up..."
          rm key.env
          sudo docker compose down
