name: CI

on:
  push:
    branches:
      - dev
      - feature/*

jobs:
  build:
    runs-on: self-hosted
    env:
      FIREBASE_KEY_JSON: ${{ secrets.FIREBASE_KEY_JSON }}
    steps:
      
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Debug GITHUBTOKEN
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

      - name: Build wait-for-services Image
        run: sudo docker build -t wait-for-services:latest --network host -f Dockerfile .

      - name: Set up Docker Compose
        run: |
        
          sudo docker-compose up --build
          sudo docker ps -a

      - name: Wait for build to finish
        run: |
          sudo docker run --network=host --rm wait-for-services

      - name: Tear down Docker Compose
        run: |
          sudo docker-compose down
